# permissions for end users to view securityevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: securityevent-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: securityevent-viewer-role
rules:
- apiGroups:
  - amtd.r6security.com
  resources:
  - securityevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - amtd.r6security.com
  resources:
  - securityevents/status
  verbs:
  - get
